[package]
name = "arpg"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", features = ["dynamic_linking"] }
bevy_dylib = { version = "0.14.0-rc.3" }
bevy_mod_picking = "0.20.1"
